#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh
#       is noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the subshell, like:
#           ksh -c './gradlew'
#       Or, you can run the script with a compliant shell itself, like:
#           bash ./gradlew
#
#   (2) This script attempts to find the Gradle home directory.
#       If you have the Gradle distribution installed elsewhere, you can set the
#       GRADLE_HOME environment variable to its location. If you don't have
#       Gradle installed, the script will download a distribution for you.
#
#   (3) Never add this script to your Git repo if you're already distributing
#       the Gradle distribution with your project.
#
#   (4) This script (gradlew) is generated from the "gradlew" and "gradlew.bat"
#       templates in the gradle/gradle-wrapper distribution. The template used
#       is the "gradlew" shell script template, located at the following
#       canonical path:
#
#           gradle/0.9/gradlew
#
#       Only the authoritative path should be used to distribute the script.
#       Do not change this path.
#
#    (5) Do not commit this script file to Git if you haven't verified that its
#        permissions are set correctly. In particular, the `gradlew` script must be
#        executable (+x). If you are using Windows, use `gradlew.bat`.
#
#    (6) You can set the GRADLE_OPTS environment variable to pass JVM arguments.
#         Example: GRADLE_OPTS="-Dorg.gradle.daemon=false"
#
#    (7) The maximum number of arguments that can be passed to the Gradle CLI is
#        65535 for all non-command line arguments.
#

# Resolve links: $0 may be a link.
app_path=$0

# Need this for daisy-chained symlinks.
while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in #(
      /*)   app_path=$link ;; #(
      *)    app_path=$(dirname "$app_path")/$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$(cd -P "${app_path%/*}" > /dev/null && pwd || echo)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined for 'unlimited' (or equivalent) so we'll attempt to query the maximum available
        # while being cautious about the maximum allowed for the current process in case it's not the maximum possible (Linux has a
        # global limit, for example). We'll then set the soft limit to the minimum of the hard limit (if set by `ulimit -Hn`) and the
        # maximum number of file descriptors suggested by the caller.
        hard_limit=$(ulimit -Hn)
        soft_limit=$(ulimit -Sn)
        max_fd="$soft_limit"
        if [ -n "$hard_limit" ] && [ "$hard_limit" -lt "$max_fd" ]; then
            max_fd=$hard_limit
        fi
        # Limit the maximum to be <= the max_fd (but we don't know the hard limit if it's 'unlimited' so we'll just assume the
        # the caller has already limited to the maximum). In POSIX sh, ulimit -n is undefined for 'unlimited' (or equivalent) so we'll
        # just fallback to the maximum number of file descriptors for the current process.
        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ]; then
            MAX_FD="$max_fd"
        fi
        ;;
      *)
        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ]; then
            # In POSIX sh, ulimit -n is undefined for 'unlimited' (or equivalent) so we'll just fallback to the maximum number of
            # file descriptors for the current process.
            MAX_FD="$(ulimit -n)"
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - we need a way to do this platform independent in the script itself.
    # The 'cygpath' command has a '-m' flag for mixed, but we need to also preserve the arguments that might be Windows paths later.
    # The easiest would be to use a 'for' loop but this would loop over the original arguments and we cannot guarantee that all of them
    # are paths. We could also eval the arguments with 'set --' but this is a platform-dependent operation.
    # Looking at the 'cygpath' documentation, it seems to be able to convert multiple arguments at once:
    #   cygpath --mixed -- ${@:?}
    # But we cannot rely on that behavior because the arguments may contain spaces. We'll just iterate over them using a while loop.
    # But we cannot use a for loop and we cannot use parameter expansion with command substitution due to the 'IFS' conflict.
    # So we'll use a while read loop.
    while IFS= read -r arg; do
        ARGS+=("$(cygpath --mixed -- "$arg")")
    done <<<"$@"
else
    ARGS=("$@")
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable that is
#     processed in a platform-independent manner (and cannot be influenced at runtime).
#   * TODO: It is not possible to write to the source of DEFAULT_JVM_OPTS currently due to the way the Gradle
#     bootstrap script is written. This will be fixed in the next major release.

exec "$JAVACMD" \
    "${ARGS[@]}" \
    -cp "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
